spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: fill
    password: fill

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
